
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LawWebSite.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Communication
{

    public int CommunicationId { get; set; }

    public int LanguageId { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Mail { get; set; }

    public string MidWeek { get; set; }

    public string Saturday { get; set; }

    public string Sunday { get; set; }

    public string MapUrl { get; set; }



    public virtual Language Language { get; set; }

}

}
