//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        public int HomeId { get; set; }
        public int LanguageId { get; set; }
        public string HomeTitle { get; set; }
        public string HomeDescription { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
        public string HomeSubTitle { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
