

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LawWebSite.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBLAW23Entities : DbContext
{
    public DBLAW23Entities()
        : base("name=DBLAW23Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Content> Contents { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<Lawyer> Lawyers { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<Blog> Blogs { get; set; }

    public virtual DbSet<UserList> UserLists { get; set; }

    public virtual DbSet<Slider> Sliders { get; set; }

    public virtual DbSet<About> Abouts { get; set; }

    public virtual DbSet<Communication> Communications { get; set; }

}

}

