
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LawWebSite.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Lawyer
{

    public int LawyerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Title { get; set; }

    public string ImgUrl { get; set; }

    public string Facebook { get; set; }

    public string Twitter { get; set; }

    public string Instagram { get; set; }

    public string Linkedin { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsAdmin { get; set; }

    public string Password { get; set; }

}

}
